/* Validate qform composition/reduction against known imaginary quadratic
 * class groups:  disc -23 (C3), -47 (C5), -71 (C7). */
#include "qform.h"
#include <stdio.h>

static int fail = 0;

static int eq(const qform_t *f, long a, long b, long c) {
    return mpz_cmp_si(f->a,a)==0 && mpz_cmp_si(f->b,b)==0 && mpz_cmp_si(f->c,c)==0;
}
static void check(int cond, const char *msg) {
    printf("  [%s] %s\n", cond ? "PASS" : "FAIL", msg);
    if (!cond) fail = 1;
}

/* g^n via repeated composition, reduced */
static void form_pow(qform_t *out, const qform_t *g, unsigned n, const mpz_t D) {
    qform_t acc, base; qform_init(&acc); qform_init(&base);
    qform_principal(&acc, D); qform_set(&base, g);
    while (n) {
        if (n & 1) qform_compose(&acc, &acc, &base, D);
        n >>= 1;
        if (n) qform_compose(&base, &base, &base, D);
    }
    qform_set(out, &acc);
    qform_clear(&acc); qform_clear(&base);
}

static void test_disc(long Dl, unsigned long ell, unsigned order, const char *tag) {
    printf("%s (disc %ld, prime %lu, expected order %u):\n", tag, Dl, ell, order);
    mpz_t D; mpz_init_set_si(D, Dl);
    qform_t g, prin, t, ti; qform_init(&g); qform_init(&prin); qform_init(&t); qform_init(&ti);
    qform_principal(&prin, D);

    /* principal has discriminant D */
    mpz_t disc; mpz_init(disc); qform_disc(disc, &prin);
    check(mpz_cmp(disc, D)==0, "principal discriminant == D");

    mpz_t E; mpz_init_set_ui(E, ell);
    int ok = qform_prime(&g, E, D);
    mpz_clear(E);
    check(ok, "prime form exists (ell splits)");
    qform_disc(disc, &g);
    check(mpz_cmp(disc, D)==0, "prime form discriminant == D");

    /* identity: principal * g == g */
    qform_compose(&t, &prin, &g, D);
    check(mpz_cmp(t.a,g.a)==0 && mpz_cmp(t.b,g.b)==0 && mpz_cmp(t.c,g.c)==0, "principal * g == g");

    /* inverse: g * g^{-1} == principal */
    qform_inverse(&ti, &g);
    qform_compose(&t, &g, &ti, D);
    check(mpz_cmp(t.a,prin.a)==0 && mpz_cmp(t.b,prin.b)==0 && mpz_cmp(t.c,prin.c)==0, "g * g^{-1} == principal");

    /* order: g^order == principal, and g^k != principal for 0<k<order */
    int order_ok = 1;
    for (unsigned k = 1; k < order; k++) {
        form_pow(&t, &g, k, D);
        if (mpz_cmp(t.a,prin.a)==0 && mpz_cmp(t.b,prin.b)==0 && mpz_cmp(t.c,prin.c)==0) order_ok = 0;
    }
    form_pow(&t, &g, order, D);
    int pow_is_prin = (mpz_cmp(t.a,prin.a)==0 && mpz_cmp(t.b,prin.b)==0 && mpz_cmp(t.c,prin.c)==0);
    check(order_ok && pow_is_prin, "g has exactly the expected order");

    mpz_clear(disc); mpz_clear(D);
    qform_clear(&g); qform_clear(&prin); qform_clear(&t); qform_clear(&ti);
}

int main(void) {
    /* disc -23: Cl = C3, generated by (2,1,3) */
    {
        mpz_t D; mpz_init_set_si(D, -23);
        qform_t g, g2, prin; qform_init(&g); qform_init(&g2); qform_init(&prin);
        qform_principal(&prin, D);
        { mpz_t two; mpz_init_set_ui(two, 2); qform_prime(&g, two, D); mpz_clear(two); } /* 2 splits for -23 */
        printf("disc -23 explicit checks:\n");
        check(eq(&prin,1,1,6), "principal(-23) == (1,1,6)");
        qform_compose(&g2, &g, &g, D);
        printf("  g=(%ld,%ld,%ld) g^2=(%ld,%ld,%ld)\n",
               mpz_get_si(g.a),mpz_get_si(g.b),mpz_get_si(g.c),
               mpz_get_si(g2.a),mpz_get_si(g2.b),mpz_get_si(g2.c));
        qform_t g3; qform_init(&g3); qform_compose(&g3,&g2,&g,D);
        check(eq(&g3,1,1,6), "g^3 == principal (order 3)");
        qform_clear(&g); qform_clear(&g2); qform_clear(&g3); qform_clear(&prin); mpz_clear(D);
    }
    test_disc(-23, 2, 3, "C3");
    test_disc(-47, 2, 5, "C5");
    test_disc(-71, 2, 7, "C7");

    printf(fail ? "\nSOME TESTS FAILED\n" : "\nALL TESTS PASSED\n");
    return fail;
}
